name: 💡 Feature Develop
description: 개발할 기능에 대해 설명해주세요
title: "Feat: "
labels: [":hammer_and_wrench: 기능"]
projects: ["ToDo-Garden/1"]

body:
  - type: textarea
    id: what-to-do
    attributes:
      label: 🛠️ 진행할 작업
      description: 진행할 작업에 대해 작성해주세요
      value: |
        - 
  - type: textarea
    id: todo-list
    attributes:
      label: 📝 TODO
      description: 진행할 작업 목록에 대해 작성해주세요 
      placeholder: 작업의 단위를 세분화하여 작성해주세요
      value: |
        - [ ] example todo
  - type: textarea
    id: backlog
    attributes:
      label: 🗂️ 백로그
      description: 관련된 백로그 링크를 작성해주세요
      value: |
        - 링크: 
  - type: textarea
    id: etc
    attributes:
      label: ⚙️ 기타
      description: 기타 참고할 만한 사안이 있으면 작성해주세요
