name: Danger SwiftLint

on:
  pull_request:

jobs:
  Danger:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - uses: actions/checkout@v4
      
      - name: Danger
        uses: 417-72KI/danger-swiftlint@v5.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
